-- Fixture mínima de integración BI, sólo en base descartable. Datos sintéticos.
CREATE TABLE tenants (id uuid PRIMARY KEY, name text NOT NULL, is_active boolean NOT NULL DEFAULT true);
CREATE TABLE categories (id uuid PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), name text NOT NULL,
    UNIQUE (tenant_id, id));
CREATE TABLE testimonial_status (id smallint PRIMARY KEY, code text NOT NULL UNIQUE);
CREATE TABLE testimonials (
    id uuid PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), category_id uuid,
    status_id smallint NOT NULL REFERENCES testimonial_status(id), rating integer NOT NULL CHECK (rating BETWEEN 1 AND 5),
    score numeric(10,4) NOT NULL DEFAULT 0,
    created_at timestamptz(3) NOT NULL DEFAULT '2024-01-01T00:00:00Z',
    updated_at timestamptz(3) NOT NULL DEFAULT now(), published_at timestamptz(3),
    image_url text, video_url text, content text NOT NULL DEFAULT 'Synthetic private text',
    author_name text NOT NULL DEFAULT 'Synthetic author', UNIQUE (tenant_id, id),
    FOREIGN KEY (tenant_id, category_id) REFERENCES categories(tenant_id, id)
);
CREATE TABLE analytics_event_types (id smallint PRIMARY KEY, code text NOT NULL UNIQUE);
CREATE TABLE analytics_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id), testimonial_id uuid NOT NULL,
    event_type_id smallint NOT NULL REFERENCES analytics_event_types(id), source text NOT NULL DEFAULT 'public',
    ip_hash text, created_at timestamptz(3) NOT NULL DEFAULT '2024-02-29T23:59:59.999Z',
    FOREIGN KEY (tenant_id, testimonial_id) REFERENCES testimonials(tenant_id, id)
);
CREATE INDEX idx_bi_fixture_testimonials ON testimonials (tenant_id, id);
CREATE INDEX idx_bi_fixture_events ON analytics_events (tenant_id, id);
CREATE TABLE feature_flags (id uuid PRIMARY KEY, name text NOT NULL UNIQUE, description text);
CREATE TABLE tenant_feature_flags (tenant_id uuid NOT NULL REFERENCES tenants(id),
    feature_flag_id uuid NOT NULL REFERENCES feature_flags(id), enabled boolean NOT NULL DEFAULT true,
    updated_at timestamptz(3) NOT NULL DEFAULT now(), PRIMARY KEY(tenant_id, feature_flag_id));
INSERT INTO testimonial_status VALUES (1, 'published'), (2, 'draft');
INSERT INTO analytics_event_types VALUES (1, 'view'), (2, 'click'), (3, 'play');
