environment                = "production"
root_domain                = "testimonialcms.com"
hosted_zone_name           = "testimonialcms.com"
app_subdomain              = "app"
api_subdomain              = "api"
vpc_cidr                   = "10.20.0.0/16"
availability_zones         = ["us-east-1a", "us-east-1b"]
public_subnet_cidrs        = ["10.20.1.0/24", "10.20.2.0/24"]
private_app_subnet_cidrs   = ["10.20.10.0/24", "10.20.11.0/24"]
private_db_subnet_cidrs    = ["10.20.20.0/24", "10.20.21.0/24"]
web_cpu                    = 512
web_memory                 = 1024
api_cpu                    = 1024
api_memory                 = 2048
web_desired_count          = 2
web_min_capacity           = 2
web_max_capacity           = 4
api_desired_count          = 2
api_min_capacity           = 2
api_max_capacity           = 4
db_instance_class          = "db.t3.small"
db_allocated_storage       = 50
db_max_allocated_storage   = 200
db_backup_retention_period = 14
db_multi_az                = true
db_deletion_protection     = true
db_skip_final_snapshot     = false
web_image_tag              = "latest"
api_image_tag              = "latest"
