environment               = "staging"
root_domain               = "testimonialcms.com"
hosted_zone_name          = "testimonialcms.com"
app_subdomain             = "staging-app"
api_subdomain             = "staging-api"
vpc_cidr                  = "10.10.0.0/16"
availability_zones        = ["us-east-1a", "us-east-1b"]
public_subnet_cidrs       = ["10.10.1.0/24", "10.10.2.0/24"]
private_app_subnet_cidrs  = ["10.10.10.0/24", "10.10.11.0/24"]
private_db_subnet_cidrs   = ["10.10.20.0/24", "10.10.21.0/24"]
web_desired_count         = 1
web_min_capacity          = 1
web_max_capacity          = 2
api_desired_count         = 1
api_min_capacity          = 1
api_max_capacity          = 2
db_instance_class         = "db.t3.micro"
db_allocated_storage      = 20
db_max_allocated_storage  = 100
db_backup_retention_period = 7
db_multi_az               = true
db_deletion_protection    = false
db_skip_final_snapshot    = true
web_image_tag             = "latest"
api_image_tag             = "latest"
